<?php
    /*
     * Implement hook_service_resources()
     */
function mobile_get_services_resources(){
    $api = array(
        'get_node' => array(
            'operations' => array(
                'retrieve'=>array(
                    'help'=> 'Retrive node content, links and body',
                    'callback' => '_mobile_get_retrieve',
                    'access_callback' => 'user_access',
                    'access arguments' => array('access content'),
                    'access arguments append' => FALSE,
                    'args' =>array(
                        array(
                            'name' => 'fn',
                            'type' => 'string',
                            'description' => 'Function to perform',
                            'source' => array('path' => '0'),
                            'optional' => TRUE,
                            'default' => '0',
                        ),
                        array(
                            'name'=>'nitems'
                            'type'=>'int',
                            'description' => 'Number of items to get',
                            'source'=>array('param' => 'nitems'),
                            'optional' => TRUE,
                            'default'=>'0',

                        )
                        array(
                            'name'=> 'nodetype',
                            'type'=> 'string',
                            'description' = 'Type of node',
                            'source' => array('param' => 'nodetype'),
                            'optional'=> TRUE,
                            'default' => '0',
                        ),
                    ),
                ),
            ),
        ),
    );              
    return $api;
}


    /* 
     * Call back function
     */
function _mobile_get_retrieve($fn, $nitems, $nodetype){
    // Safe checking:
    $nitems = intval($nitems);
    return resource_restapi_get($nitems, $nodetype);
}
    /**
    *  * Gets blog posts
    *   */
function resource_restapi_get($nitems, $nodetype) {
    // Compose query
    $query = db_select('node','n');
    $query->join('field_data_field_link', 'l', '(n.nid = l.entity_id)'); 
    $query->join('field_data_body', 'b','(b.entity_id = n.id)');
    $query->fields('n', array('title'));
    $query->addField('l', 'field_link_value');
    $query->addField('b', 'body_value');
    $query->condition('n.type', 'headline', '='); 
    // Limit by 
    if($nitems<50 && $nitems>=0){
        $query->range(0, $nitems);
    }
    else {($query->range(0,50);}
    $items = $query->execute()->fetchAll();
    return 
            $items;
}



